services:
  api:
    restart: always
    build:
      context: ./api
    ports:
      - "9701:8080"
    environment:
      - ENV=prod
      - LOG_LEVEL=debug
      - JWT_SECRET=${JWT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_REPOS_DIR=/root/repos
      - GOTENBERG_ADDR=http://gotenberg:3000
    volumes:
      - ./api/repos:/root/repos

  ui:
    restart: always
    build:
      context: ./ui
      args:
        - NEXT_PUBLIC_API_ADDR=https://api.gitprint.me
        - NODE_ENV=production
    ports:
      - "9702:3000"

  gotenberg:
    restart: always
    image: gotenberg/gotenberg:8
    environment:
      - DEFAULT_WAIT_TIMEOUT=30
    ports:
      - "9703:3000"

  nginx:
    restart: always
    image: nginx:latest
    depends_on:
      - ui
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - ./conf/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
      - ./data/certbot/www:/var/www/certbot
      - ./data/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"

  certbot:
    restart: always
    image: certbot/certbot:latest
    volumes:
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
